# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:    pretty

# Page info
title:        Peter's private space
description:  'to develop skills, share ideas and experience'
domain:       roth.su
url:          https://roth.su
baseurl:      ''

# About me / contact
author:
  name:       Peter Roth
  url:        https://roth.su
  email:      peter@roth.su

# Plugins
plugins: [jekyll-feed, jekyll-paginate, jekyll-sitemap]
paginate: 5
paginate_path: "page:num"
