# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Page info
title:               Peter's sandbox
description:         'to develop skills, share ideas and experience'
url:                 http://roth.su
baseurl:             ''

# About me / contact
author:
  name:              Peter Roth
  url:               http://roth.su
  email:             peter@roth.su

# Plugins
plugins: [jekyll-feed, jekyll-paginate]
paginate: 5
paginate_path: "page:num"
